### ISSUE TITLE
Inline rating with text

### ISSUE THREAD

**Issue by iad42** [fraserxu/ionic-rating#22]
Hi, i have a problem with making html/css for displaying rating start + a text note. like this:

Satisfaction        * * * * *

So i need it inline

Here is my current code. labelbox draws a box, very similar to ionic label

```HTML
        <label class="item item-input">
          <input type="date" placeholder="Date">
        </label>
        <label class="item item-input">
          <input type="time" placeholder="Time">
        </label>

        <div class="labelbox">
          Satisfaction 
          <rating ng-model="rate" max="max"></rating>
       </div>
```

```CSS
.labelbox {
	border: 1px solid rgb(215,215,215);
	border-top-right-radius: 0px;
	border-top-left-radius: 0px;
	border-bottom-left-radius: 3px;
	border-bottom-right-radius: 3px;
}
```

<img width="557" alt="screen shot 2015-09-24 at 22 41 13" src="https://cloud.githubusercontent.com/assets/7037785/10081241/66f59a98-630d-11e5-8e49-af9a5be22ae8.png">
